import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
   tutorialSidebar: [
    'intro', // 加载的第一个文件，可以作为菜单
    // 'platforms', //加载的第二个文件，可以作为菜单
    {
      type: 'autogenerated',
      dirName: 'devices'}
  ],

   snapemuSidebar: [
    'platforms',
    // 'intro',
    {
      type: 'autogenerated',
      dirName: 'platform',
    },
   ]

  // tutorialSidebar: [
  //   'intro',
  //   'lora',
  //   {
  //     type: 'category',
  //     label: 'LoRa Devices123',
  //     items: [
  //       'lora/lora-32/lora-32',
  //       'lora/lora-32/wifi-lora-32-v3',
  //     ],
  //   },
  // ],
};

export default sidebars;
